language: R
cache: packages
sudo: false
warnings_are_errors: false

r:
  - oldrel
  - release
  - devel
os:
  - linux
  - osx

apt_packages:
  - libgit2-dev

r_packages:
  - fst

after_success:
  - Rscript -e 'library(covr); codecov(quiet = FALSE)'
